### ISSUE TITLE
Pré-filtros

### ISSUE THREAD

**Issue by brunobrr** [brunobrr/risk_assessment_flora_Brazil_I#31]
@kguidonimartins, estes são os filtros utilizamos nessa etapa. Inseri os scripts antigos como ponto de partida, mas fique à vontade para modificar e criar outros se necessário.

#### TODO

- [x] 1. Usar a função que o @sjevelazco  criou para corrigir xy trocados 
- [x] 2. Remover registros com coordenadas inválidas
- [x] 3. Remover registros sem lat ou sem long
- [x] 4. Registros em nome ou com nome vazio
- [x] 5. Registros fora do país selecionado
- [x] 6. Remover registros fósseis ou com origem duvidosa
- [x] 7. Salvar tabela na de nomes sem coordenadas (x ou y) mas que contém informações sobre localidade

### Descrição

1. Usar a função que o @sjevelazco  criou para corrigir xy trocados.: Essa função substitui diretamente o xy trocados pelos corretos na tabela inserida e retorna uma tabela com o xy original e corrigido. Essa tabela poder ser salva no pasta `Output/Check/01_correct_xy.csv` (ver mais detalhes sobre organização das pastas no issue #32 )

Os seguintes filtros podem reportados como T ou F em uma tabela de resultados. Por exemplo, algo como...

```r
res$correct_xy <- correct_xy 
res$rem_fossil_records <- rem_fossil_records 
```

Digo isso para que toda a base de dados seja sempre analisada em cada um dos filtros.

2. Remover registros com coordenadas inválidas:

```r
valid_coords <- 
data_01 %>% cc_val(
  .,
  lon = "longitude",
  lat = "latitude",
  verbose = T,
  value = "flagged"
)
```

3. Remover registros sem lat ou sem long

4. Registros em nome ou com nome vazio

5. Registros fora do país selecionado

Talvez seja melhor criar uma função para o script abaixo para que a pessoa consiga informar x, y, nome do país e a distância do buffer

```r
m <- rworldmap::getMap() # rworldmap
brazil <- m[which(m$NAME == "Brazil"), ]
brazil@data <- brazil@data %>% dplyr::select(ADMIN)
brazil@data$fill <- 1`

OCC <- data_01 %>% dplyr::select(longitude, latitude)
selec_points <- raster::extract(brazil, OCC, buffer = 2000)
data_01$.inBrazil <- selec_points$fill
```

6. Remover registros fósseis ou com origem duvidosa

```r
data_01 <- data_01 %>%
  mutate(.provenance = if_else(basisOfRecord %in% 
                                 c("Amost", "DrawingOrPhotograph" ,
                                   "Dupli", "EX" , "E", "Extra",
                                   "F", "FOSSIL_SPECIMEN",   
                                   "FossilSpecimen", "HS", "HUCP",
                                   "MACHINE_OBSERVATION",
                                   "MachineObservation", "MultimediaObject",
                                   "QQQQQ", "REPET", "RON", "V",  
                                   "X", "XS"), FALSE, TRUE)) 
```

7. Salvar tabela na de nomes sem coordenadas (x ou y) mas que contém informações sobre localidade (eg. Outputs/Check/01_xy_from_locality.csv)

**Comment by brunobrr** [comment]
@kguidonimartins as funções bdc_flag_no_xy e bdc_flag_invalid_xy são iguais? Isso mesmo?

**Comment by kguidonimartins** [comment]
oi Bruno, são idênticas! Falta de atenção minha... Acho que podemos deletar
uma delas. O que você acha?

**Comment by brunobrr** [comment]
@kguidonimartians podemos sim. 

Estou fazendo alguns teste aqui e me sugiram algumas ideias. Gostaria de ouvir de você se vale a pena: 

1. Inserir argumentos nas funções para torna-las mais gerais
- bdc_flag_outside_xy (data, long, lat)  >> Aqui podemos substuir o nome da função para "bdc_flag_invalid_xy"
- bdc_flag_invalid_xy (data, long, lat)   >> Podemos substituir para "bdc_flag_no_xy (para ficar similar a função "bdc_flag_no_name"
- bdc_flag_no_name(data, sci_name) 

O que você acha?

**Comment by kguidonimartins** [comment]
Acho interessante. Os novos argumentos podem permitir que essas funções sejam usadas em outros conjuntos de dados que não seguem o padrão de nomes de colunas que estabelecemos no início do workflow.

**Comment by brunobrr** [comment]
Maravilha, eu só fiquei na dúvida como adicionar os argumentos na função. Você pode fazer as modificações em uma das funções e faço o restante? Na maioria das nossas funções, se não me engano, os argumentos devem ser colocados entre aspas. É possível fazer isso usando dplyr?

**Comment by kguidonimartins** [comment]
Acho que sim, Bruno. Vou modificar a primeira e subir.

**Comment by kguidonimartins** [comment]
@brunobrr, subi em #62 um exemplo de como usar as aspas dentro do dplyr. Avise se tiver problemas com os outros verbos.

**Comment by brunobrr** [comment]
Valeu, Karlo!!!

**Comment by brunobrr** [comment]
@Karlo, não consegue fazer a função bdc_flag_invalid_xy funcionar. Você pode dar uma olhada, por favor? Utilizei o seguinte conjunto de dados como exemplo.

long <- c(20.02, 181.00,  20.02,  20.02,  20.02,  20.02,  20.02)
lat <-  c("Ontem", "20.02", "NA",    NA,      ",",     "20.2",  "-92")

e <- data.frame(long, lat)

**Comment by kguidonimartins** [comment]
Confira se agora vai...

**Comment by brunobrr** [comment]
Done
